version: '2'

networks:
  byfn:

services:
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  ../Base/docker-compose-base.yaml
      service: peer0.org1.example.com
    networks:
      - byfn