version: '2'

networks:
  byfn:

services:

  orderer1.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.example.com
    container_name: orderer1.example.com
    networks:
      - byfn