version: '2'

networks:
  byfn:

services:
  kafka0.example.com:
      container_name: kafka0.example.com
      extends:
        file: ../Base/docker-compose-base.yaml
        service: kafka0.example.com
      networks:
        - byfn         
